apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/webapp:1bd8c78b9681d36dddd8b8ac848b868604da9dda 
          ports:
            - containerPort: 5000