apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/webapp:3fd93bfeeedfe6ef803ae4d3be74b65264ec8561 
          ports:
            - containerPort: 5000