apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: 440896245143.dkr.ecr.us-west-2.amazonaws.com/webapp:b60d1c1b65c0f15c52b3275a371f9bbab0dc5fbf 
          ports:
            - containerPort: 5000